generator:
  old:
    transaction: 1000000000
    user: 1000000
    product: 100000
    concurrency: 1000
  executor:
    core-pool-size: 1000
    max-pool-size: 1000
    keep-alive-time: 30
    work-queue-size: 1010